- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     state: present
  tasks:
   - name: Configure IPv4 addresses.
     fmgr_firewall_address:
        bypass_validation: False
        adom: root
        state: "{{ state }}"
        firewall_address:
           allow-routing: disable
           associated-interface: any
           fqdn: fortinet.com
           name: ansible-fqdn
           type: fqdn
          
   - name: Configure IPv4 address groups
     fmgr_firewall_addrgrp:
        bypass_validation: False
        adom: root
        state: "{{ state }}"
        firewall_addrgrp:
           allow-routing: disable
           color: 0
           member: 'ansible-fqdn' # IPv4 address name
           name: 'ansible-addrgrp4' # could not the same with other group, adress name, including IPv6 group and address 

   - name: Configure IPv4 policies.
     fmgr_pkg_firewall_policy:
        bypass_validation: False
        adom: root
        pkg: FG_ansible # package name
        state: "{{ state }}"
        pkg_firewall_policy:
           srcaddr: all
           action: accept #<value in [deny, accept, ipsec, ...]>
           comments: ansible-comment
           dstaddr: ansible-addrgrp4
           dstintf: any
           name: ansible-policy
           nat: disable
           policyid: 1
           schedule: always
           service: ALL
           srcaddr: all
           srcintf: any
           status: enable

   - name: Install for policy package root
     fmgr_securityconsole_install_package:
        securityconsole_install_package:
          adom: root
          flags:
             - preview
          pkg: FG_ansible
          scope:
            - name: Fortigate_VM
              vdom: root
              
   - name: Install policies to device from preview cache.
     fmgr_securityconsole_package_commit:
        bypass_validation: False
        workspace_locking_adom: root
        workspace_locking_timeout: 300
        rc_succeeded: 0
        rc_failed: -2
        securityconsole_package_commit:
           adom: root
           scope:
             - name: Fortigate_VM
               vdom: root